aws_image_region                 = "us-east-2"
ami_name                         = "my-astraios-webservice"
instance_type                    = "t2.small"
ws_war_path                      = "astraios-1.0-SNAPSHOT.war"
aws_ws_ssl_cert_file_path        = "ssl-cert-file.example"
aws_ws_ssl_cert_key_file_path    = "ssl-cert-key-file.example"
aws_ws_nginx_config_file_path    = "nginx.config.example"
aws_ws_filebeat_config_file_path = "filebeat.yml.example"
