# Copyright Paion Data
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'setup'
description: 'CI/CD setup, such as installing JDK and fetch runbook'

inputs:
  runbooks-repo-token:
    description: 'hashicorp-aws-runbooks fine-grained PAT token;'
    required: true
  data-models-repo-token:
    description: 'Astraios data models repo fine-grained PAT token;'
    required: true
  data-models-repo-org:
    description: 'Astraios data models repo owner, e.g. paion-data'
    required: true
  data-models-repo-name:
    description: 'Astraios data models repo name, e.g. my-jpa-data-model'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Checkout HashiCorp deployment tool
      shell: bash
      run: git clone https://github.com/QubitPi/hashicorp-aws.git ../hashicorp-aws
    - name: Checkout HashiCorp deployment config files
      shell: bash
      run: git clone https://${{ inputs.runbooks-repo-token }}@github.com/QubitPi/hashicorp-aws-runbooks.git ../hashicorp-aws-runbooks
    - name: Load Packer variable file
      shell: bash
      run: cp ../hashicorp-aws-runbooks/paion-data/astraios/aws-ws.pkrvars.hcl ../hashicorp-aws/hashicorp/webservice/images/aws-ws.auto.pkrvars.hcl
    - name: Load Terraform variable file
      shell: bash
      run: cp ../hashicorp-aws-runbooks/paion-data/astraios/aws-ws.tfvars ../hashicorp-aws/hashicorp/webservice/instances/aws-ws.auto.tfvars
    - name: Load Maven settings.xml
      shell: bash
      run: |
        if [[ ${{ inputs.data-models-repo-org }} == "QubitPi" ]]; then
          cp ../hashicorp-aws-runbooks/paion-data/astraios/settings.test.xml ~/.m2/settings.xml
        else
          cp ../hashicorp-aws-runbooks/paion-data/astraios/settings.xml ~/.m2/settings.xml
        fi
    - name: Load webservice properties files
      shell: bash
      run: |
        cp ../hashicorp-aws-runbooks/paion-data/astraios/oauth.properties src/main/resources/
        cp ../hashicorp-aws-runbooks/paion-data/astraios/application.properties src/main/resources/
        cp ../hashicorp-aws-runbooks/paion-data/astraios/jpadatastore.properties src/main/resources/
    - name: Install data models
      shell: bash
      run: |
        git clone https://${{ inputs.data-models-repo-token }}@github.com/${{ inputs.data-models-repo-org }}/${{ inputs.data-models-repo-name }}.git ../jpa-models
        cd ../jpa-models
        mvn clean install
